import db from '../db';

export interface Asset {
	id: string;
	project_id: string;
	filename: string;
	rel_path: string;
	mime: string | null;
	size_bytes: number | null;
	thumb_path: string | null;
	caption: string | null;
	created_at: string;
}

export function listAssets(projectId: string): Asset[] {
	return db
		.prepare('SELECT * FROM assets WHERE project_id = ? ORDER BY created_at DESC')
		.all(projectId) as Asset[];
}

export function getAsset(id: string): Asset | undefined {
	return db.prepare('SELECT * FROM assets WHERE id = ?').get(id) as Asset | undefined;
}

export interface AssetInput {
	filename: string;
	rel_path: string;
	mime: string | null;
	size_bytes: number | null;
	thumb_path: string | null;
	caption?: string | null;
}

// The id is generated by the caller (server/assets.ts) so the on-disk filenames and this row
// share the same id — keeps upload + insert trivially reconcilable if one half fails.
export function createAsset(id: string, projectId: string, input: AssetInput): Asset {
	const now = new Date().toISOString();
	db.prepare(
		`INSERT INTO assets (id, project_id, filename, rel_path, mime, size_bytes, thumb_path, caption, created_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
	).run(
		id,
		projectId,
		input.filename,
		input.rel_path,
		input.mime,
		input.size_bytes,
		input.thumb_path,
		input.caption ?? null,
		now
	);
	return getAsset(id)!;
}

export function updateAssetCaption(id: string, caption: string | null): Asset | undefined {
	if (!getAsset(id)) return undefined;
	db.prepare('UPDATE assets SET caption = ? WHERE id = ?').run(caption, id);
	return getAsset(id);
}

// Also clears the project's cover_asset_id if it pointed at this asset, so nothing dangles.
export function deleteAssetAndClearCover(id: string): void {
	const asset = getAsset(id);
	if (!asset) return;
	db.prepare('DELETE FROM assets WHERE id = ?').run(id);
	db.prepare('UPDATE projects SET cover_asset_id = NULL WHERE id = ? AND cover_asset_id = ?').run(
		asset.project_id,
		id
	);
}
