import fs from 'fs/promises';
import path from 'path';
import sharp from 'sharp';
import { env } from '$env/dynamic/private';

const DATA_DIR = env.DATA_DIR ?? './data';
export const ASSETS_DIR = path.join(DATA_DIR, 'assets');

const IMAGE_MIME = new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/avif']);

// Deliberately excludes image/svg+xml (can carry scripts), text/html, and anything executable —
// served assets are never allowed to be a type a browser would treat as active content.
const ALLOWED_MIME = new Set([
	...IMAGE_MIME,
	'application/pdf',
	'text/plain',
	'text/markdown',
	'application/zip',
	'video/mp4',
	'video/webm'
]);

function maxUploadBytes(): number {
	const mb = Number(env.MAX_UPLOAD_MB) || 200;
	return mb * 1024 * 1024;
}

export class UploadError extends Error {}

function sanitizeFilename(name: string): string {
	const base = path.basename(name).replace(/[^\w.-]+/g, '_');
	return base || 'file';
}

export interface SavedUpload {
	filename: string;
	rel_path: string;
	mime: string;
	size_bytes: number;
	thumb_path: string | null;
}

// `id` is generated by the caller so the on-disk name and the DB row share it.
export async function saveUpload(id: string, projectId: string, file: File): Promise<SavedUpload> {
	if (!ALLOWED_MIME.has(file.type)) {
		throw new UploadError(`File type "${file.type || 'unknown'}" isn't allowed`);
	}
	if (file.size > maxUploadBytes()) {
		throw new UploadError(`File is larger than the ${Math.round(maxUploadBytes() / 1024 / 1024)} MB limit`);
	}

	const projectDir = path.join(ASSETS_DIR, projectId);
	await fs.mkdir(projectDir, { recursive: true });

	const filename = sanitizeFilename(file.name);
	const storedName = `${id}-${filename}`;
	const buffer = Buffer.from(await file.arrayBuffer());
	await fs.writeFile(path.join(projectDir, storedName), buffer);

	let thumbRelPath: string | null = null;
	if (IMAGE_MIME.has(file.type)) {
		const thumbName = `${id}-thumb.webp`;
		try {
			await sharp(buffer)
				.resize(400, 400, { fit: 'inside', withoutEnlargement: true })
				.webp({ quality: 80 })
				.toFile(path.join(projectDir, thumbName));
			thumbRelPath = path.join(projectId, thumbName);
		} catch {
			// Corrupt/unsupported image data — keep the original upload, just skip the thumbnail.
		}
	}

	return {
		filename,
		rel_path: path.join(projectId, storedName),
		mime: file.type,
		size_bytes: buffer.byteLength,
		thumb_path: thumbRelPath
	};
}

// Resolves a stored relative path to an absolute one, refusing anything that would
// escape ASSETS_DIR (defense in depth — rel_path always comes from our own writes, never
// directly from user input, but this keeps the file-serving routes safe regardless).
export function absoluteAssetPath(relPath: string): string {
	const base = path.resolve(ASSETS_DIR);
	const resolved = path.resolve(base, relPath);
	if (resolved !== base && !resolved.startsWith(base + path.sep)) {
		throw new UploadError('Invalid asset path');
	}
	return resolved;
}

export async function deleteUploadFiles(relPath: string, thumbRelPath: string | null): Promise<void> {
	await fs.rm(absoluteAssetPath(relPath), { force: true });
	if (thumbRelPath) await fs.rm(absoluteAssetPath(thumbRelPath), { force: true });
}
